name: Get storages buckets
on: 
  workflow_dispatch
jobs:
  get-secret:
    runs-on: ubuntu-latest
    environment: qa
    # Add "id-token" with the intended permissions.

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    # Configure Workload Identity Federation via a credentials file.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        
        token_format: 'access_token'
         workload_identity_provider: 'projects/776048919216/locations/global/workloadIdentityPools/github/providers/my-repo'
         service_account: 'my-service-account@project-0092-prod.iam.gserviceaccount.com'

       # workload_identity_provider: 'projects/776048919216/locations/global/workloadIdentityPools/github/providers/my-repo'
       # service_account: 'svc-aws-service-account@project-0092-prod.iam.gserviceaccount.com'

    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # Now you can run gcloud commands authenticated as the impersonated service account.
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
         gsutil ls  gs://test_bucket_own_333 
